/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emuladorsql.ui;

import java.awt.event.MouseAdapter;

import emuladorsql.cup.Componente;
import emuladorsql.manejadorArchivo.EditadorIde;
import emuladorsql.manejadorArchivo.ManejadorCsv;
import emuladorsql.manejadorArchivo.ManejadorIde;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTextArea;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author sergio
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private File file;
    private Componente raiz;
    private DefaultMutableTreeNode dummie = new DefaultMutableTreeNode("Right Click + Leaf");

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        menuOpen = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Ctrl+O ->Open");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        jTextArea2.setBackground(new java.awt.Color(79, 78, 102));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(254, 254, 254));
        jTextArea2.setRows(5);
        jTextArea2.setText(">sql\n");
        jScrollPane3.setViewportView(jTextArea2);

        jMenu1.setText("File");

        menuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNew.setText("New");
        menuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewActionPerformed(evt);
            }
        });
        jMenu1.add(menuNew);

        menuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuOpen.setText("Open");
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        jMenu1.add(menuOpen);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.showOpenDialog(this);
        file = fileChooser.getSelectedFile();
        if (file != null) {
            IngresoNombre ingresoNombre = new IngresoNombre(this, true, file.getPath());
            ingresoNombre.setVisible(true);
            if (ingresoNombre.getFile() != null) {
                ManejadorIde mi = new ManejadorIde();
                mi.abrirProyectoIde(ingresoNombre.getFile(), this);
            }
        }

    }//GEN-LAST:event_menuNewActionPerformed

    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.showOpenDialog(this);

        file = fileChooser.getSelectedFile();
        if (file != null) {
            ManejadorIde manejadorIde = new ManejadorIde();
            manejadorIde.abrirProyectoIde(file, this);
        }

    }//GEN-LAST:event_menuOpenActionPerformed

    public void recibirRaiz(Componente raiz) {
        this.raiz = raiz;
        dibujarArbol();
    }

    private void dibujarArbol() {
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode(raiz);
        ArrayList<Componente> comp = raiz.getComponetes();
        if (comp != null) {
            for (int i = 0; i < comp.size(); i++) {
                agregarNodo(raiz.getComponetes().get(i), treeNode1);
            }
        } else {

            treeNode1.add(dummie);
        }

        jTree1.setModel(new DefaultTreeModel(treeNode1));
        agregarMouseLisener();
    }

    private void agregarNodo(Componente com, DefaultMutableTreeNode treeNode) {
        DefaultMutableTreeNode tN = new DefaultMutableTreeNode(com);

        if (com.getComponetes() != null) {
            for (int i = 0; i < com.getComponetes().size(); i++) {

                if (com.getComponetes().get(i).getComponetes() != null) {
                    agregarNodo(com.getComponetes().get(i), tN);
                } else {
                    DefaultMutableTreeNode tN2 = new DefaultMutableTreeNode(com.getComponetes().get(i));

                    if (com.getComponetes().get(i).getUbicacion() == null) {
                        tN2.add(dummie);
                    }
                    tN.add(tN2);
                }

            }
        } else {
            if (com.getUbicacion() == null) {
                tN.add(dummie);
            }
        }

        treeNode.add(tN);

    }

    private void agregarMouseLisener() {
        jTree1.getSelectionModel().setSelectionMode(
                TreeSelectionModel.DISCONTIGUOUS_TREE_SELECTION);

        jTree1.addMouseListener(new MyMouseAdapter());
    }

    private class MyMouseAdapter extends MouseAdapter {

        private void myPopupEvent(MouseEvent e) {
            int x = e.getX();
            int y = e.getY();
            JTree tree = (JTree) e.getSource();
            TreePath path = tree.getPathForLocation(x, y);
            if (path == null) {
                return;
            }
            DefaultMutableTreeNode rightClickedNode = (DefaultMutableTreeNode) path
                    .getLastPathComponent();

            TreePath[] selectionPaths = tree.getSelectionPaths();

            boolean isSelected = false;
            if (selectionPaths != null) {
                for (TreePath selectionPath : selectionPaths) {
                    if (selectionPath.equals(path)) {
                        isSelected = true;
                    }
                }
            }
            if (!isSelected) {
                tree.setSelectionPath(path);
            }
            if (rightClickedNode != dummie) {
                if (rightClickedNode.isLeaf()) {
                    JPopupMenu popup = new JPopupMenu();
                    final JMenuItem refreshMenuItem = new JMenuItem("Open");
                    refreshMenuItem.addActionListener(ev -> openArchivo(rightClickedNode));
                    popup.add(refreshMenuItem);

                    final JMenuItem refreshMenuItem2 = new JMenuItem("Delete");
                    refreshMenuItem2.addActionListener(ev -> System.out.println("Delete!"));
                    popup.add(refreshMenuItem2);
                    popup.show(tree, x, y);
                } else {
                    JPopupMenu popup = new JPopupMenu();
                    final JMenuItem refreshMenuItem = new JMenuItem("New File");
                    refreshMenuItem.addActionListener(ev -> openArchivo(rightClickedNode));
                    popup.add(refreshMenuItem);

                    final JMenuItem refreshMenuItem2 = new JMenuItem("New Carpet");
                    refreshMenuItem2.addActionListener(ev -> agregarCarpeta(rightClickedNode.getPath(), PantallaPrincipal.this));
                    popup.add(refreshMenuItem2);

                    final JMenuItem refreshMenuItem3 = new JMenuItem("Delete");
                    refreshMenuItem3.addActionListener(ev -> System.out.println("Delete!"));
                    popup.add(refreshMenuItem3);
                    popup.show(tree, x, y);
                }
            }

        }

        public void agregarCarpeta(TreeNode[] dmtn, PantallaPrincipal pp) {
            String sPath = file.getPath();
            for (int i = 1; i < dmtn.length; i++) {
                sPath += "/" + dmtn[i];

            }
            NombreArchivoNuevo nan = new NombreArchivoNuevo(pp, rootPaneCheckingEnabled, NombreArchivoNuevo.TIPO_CARPETA, sPath, dmtn[dmtn.length - 1], file);
            nan.setVisible(true);
            if (nan.isIngresado()) {

                ManejadorIde manejadorIde = new ManejadorIde();
                manejadorIde.abrirProyectoIde(file, pp);
            }
        }

        public void mousePressed(MouseEvent e) {
            if (e.isPopupTrigger()) {
                myPopupEvent(e);
            }
        }

        public void mouseReleased(MouseEvent e) {
            if (e.isPopupTrigger()) {
                myPopupEvent(e);
            }
        }

        public void openArchivo(DefaultMutableTreeNode dtm) {
            ManejadorCsv cs = new ManejadorCsv();
            if (cs.agregarArchivo(((Componente) dtm.getUserObject()).getUbicacion(), jTabbedPane1) == false) {
                JTextArea jtxt = new JTextArea();
                jTabbedPane1.add(jtxt);
                jtxt.setText("Error");
            }

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JMenuItem menuOpen;
    // End of variables declaration//GEN-END:variables
}
