
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 10 03:38:26 CST 2020
//----------------------------------------------------

package emuladorsql.jflex;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int NOM = 5;
  public static final int UBI = 6;
  public static final int ERROR = 15;
  public static final int CAR = 3;
  public static final int PRO = 2;
  public static final int IGU = 11;
  public static final int EOF = 0;
  public static final int DIAC = 10;
  public static final int ABR = 7;
  public static final int DIAA = 9;
  public static final int error = 1;
  public static final int ARC = 4;
  public static final int COM = 12;
  public static final int NOMBRE = 13;
  public static final int PATH = 14;
  public static final int CER = 8;
}

