
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 16 05:13:18 CST 2020
//----------------------------------------------------

package emuladorsql.jflex;

/** CUP generated class containing symbol constants. */
public class SimboloSql {
  /* terminals */
  public static final int AND = 19;
  public static final int PUNTO = 18;
  public static final int INSERTAR = 3;
  public static final int OR = 20;
  public static final int ELIMINAR = 5;
  public static final int SINPUNTOYCOMA = 26;
  public static final int ERROR = 30;
  public static final int CERIG = 22;
  public static final int COM = 16;
  public static final int PARC = 13;
  public static final int POR = 17;
  public static final int PARA = 12;
  public static final int NOM = 10;
  public static final int NUM = 29;
  public static final int FILTRAR = 7;
  public static final int VALORES = 9;
  public static final int ASIGNAR = 8;
  public static final int ACTUALIZAR = 4;
  public static final int COMA = 15;
  public static final int NOMBRE = 27;
  public static final int EOF = 0;
  public static final int ABRIG = 21;
  public static final int ABR = 24;
  public static final int error = 1;
  public static final int IGU = 14;
  public static final int CER = 25;
  public static final int PC = 11;
  public static final int EN = 6;
  public static final int PATH = 28;
  public static final int DIF = 23;
  public static final int SELECCIONAR = 2;
}

