
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 19 05:19:26 CST 2020
//----------------------------------------------------

package emuladorsql.jflex;

/** CUP generated class containing symbol constants. */
public class SimboloSql {
  /* terminals */
  public static final int AND = 18;
  public static final int PUNTO = 17;
  public static final int INSERTAR = 3;
  public static final int OR = 19;
  public static final int ELIMINAR = 5;
  public static final int SINPUNTOYCOMA = 25;
  public static final int ERROR = 29;
  public static final int CERIG = 21;
  public static final int COM = 15;
  public static final int PARC = 12;
  public static final int PARA = 11;
  public static final int POR = 16;
  public static final int NUM = 28;
  public static final int FILTRAR = 7;
  public static final int VALORES = 9;
  public static final int ASIGNAR = 8;
  public static final int ACTUALIZAR = 4;
  public static final int COMA = 14;
  public static final int NOMBRE = 26;
  public static final int EOF = 0;
  public static final int ABRIG = 20;
  public static final int ABR = 23;
  public static final int error = 1;
  public static final int IGU = 13;
  public static final int CER = 24;
  public static final int PC = 10;
  public static final int EN = 6;
  public static final int PATH = 27;
  public static final int DIF = 22;
  public static final int SELECCIONAR = 2;
}

