
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 18 19:48:52 CST 2020
//----------------------------------------------------

package emuladorsql.jflex.Secundario;

/** CUP generated class containing symbol constants. */
public class SimbolosCSV {
  /* terminals */
  public static final int COMA = 3;
  public static final int error = 1;
  public static final int TODO = 2;
  public static final int ENTER = 4;
  public static final int EOF = 0;
}

