
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 18 17:26:35 CST 2020
//----------------------------------------------------

package emuladorsql.jflex.Secundario;

/** CUP generated class containing symbol constants. */
public class SimboloPuntoyComa {
  /* terminals */
  public static final int error = 1;
  public static final int TODO = 2;
  public static final int EOF = 0;
  public static final int PYC = 3;
}

